[build]
  command = "npm ci && npm run build"
  publish = "dist"
  base = "/"

[build.environment]
  NODE_VERSION = "18.17.0"
  NPM_FLAGS = "--legacy-peer-deps"
  NPM_CONFIG_PRODUCTION = "false"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 